### PR TITLE
Update location.js

### PR DESCRIPTION
**Pull request by mosch**
Add the origin response to the client config to make it accessible in other interceptors.

### CODE REVIEW

**Comment by scothis** [comment]
@mosch thinking about this a bit more. What should the semantics be when there are multiple intermediate requests? First write wins, last write wins, track them all somehow?

**Comment by mosch** [comment]
Every request can only have one prior request, so being able to access all requests made, we'll be albe to see all intermediate requests. what do you think?

**Comment by scothis** [comment]
It's true that each logical request may only have a single prior request, this doesn't quite play out correctly since the request object is reused in the case of the retry interceptor. In that case what do you think 'prior' should represent?

**Comment by mosch** [comment]
I think most useful will be the last request that happend, everything else would be confusing

**Pull request closed without merging**
