### PR TITLE
Patched module loading to support for web-workers

### PR DESCRIPTION
**Pull request by 1313**
As window does not exist as a global object inside a web worker i wrote a simple patch to switch window for self if window is undefined.

This was a quick fix, might need to give it some more though, just wanted to make you aware of the issue.

Without this fix, if you use the client inside a web worker a lot of TypeError undefined will be thrown due to the issue mentioned above.

Cheers!
Per

### CODE REVIEW

**Comment by 1313** [comment]
Err, missed

**Comment by scothis** [comment]
@1313 did you mean to close this PR? Web Works are an environment I have not tested rest.js in, but would like to make work if there are issues.

**Comment by 1313** [comment]
Hey, I was in a hurry so my code was not working very well and had a lot of bad commits with nonsense commit messages. But the issue is still there, I intend to open a new pull request with a better description and fix of the issue.

The main reason is accessing the global resources within the webworker, stuff like location etc. 
Per

**Comment by scothis** [comment]
Look forward to it. Please ask if you run into anything strange or just need an opinion.

**Pull request closed without merging**
